version: "3.9"

services:
  telegram-userbot:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install telethon requests && python bot.py"
    environment:
      - API_ID=37536236
      - API_HASH=b71767892b510a465d47e03dc45405d9
      - N8N_WEBHOOK=https://serven8.automatizacomea.cloud/webhook/telegram-group-listener
    restart: always