version: '3.8'

services:
  telegram-userbot:
    image: ghcr.io/nskha/telegram-n8n-userbot:latest
    restart: unless-stopped
    volumes:
      - telegram-data:/app
    environment:
      - API_ID=37536236
      - API_HASH=b71767892b510a465d47e03dc45405d9
      - N8N_WEBHOOK=https://serven8.automatizacomea.cloud/webhook/telegram-group-listener

volumes:
  telegram-data:
